# Generated by Django 5.2.17 on 2026-08-27 10:46

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archived')),
            ],
            options={
                'verbose_name': 'wall',
                'verbose_name_plural': 'walls',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='climbs_wall_name_ci_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ClimbingRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('discipline', models.CharField(choices=[('route', 'Routes'), ('boulder', 'Boulder')], max_length=10, verbose_name='discipline')),
                ('official_grade', models.CharField(blank=True, choices=[('4a', '4a'), ('4a+', '4a+'), ('4b', '4b'), ('4b+', '4b+'), ('4c', '4c'), ('4c+', '4c+'), ('5a', '5a'), ('5a+', '5a+'), ('5b', '5b'), ('5b+', '5b+'), ('5c', '5c'), ('5c+', '5c+'), ('6a', '6a'), ('6a+', '6a+'), ('6b', '6b'), ('6b+', '6b+'), ('6c', '6c'), ('6c+', '6c+'), ('7a', '7a'), ('7a+', '7a+'), ('7b', '7b'), ('7b+', '7b+'), ('7c', '7c'), ('7c+', '7c+'), ('8a', '8a'), ('8a+', '8a+'), ('8b', '8b'), ('8b+', '8b+'), ('8c', '8c'), ('8c+', '8c+'), ('9a', '9a'), ('9a+', '9a+'), ('9b', '9b'), ('9b+', '9b+'), ('9c', '9c')], max_length=3, verbose_name='official grade')),
                ('is_project', models.BooleanField(default=False, verbose_name='project')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archived')),
                ('route_setters', models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'RouteSetter', 'is_active': True}, related_name='set_climbing_routes', to=settings.AUTH_USER_MODEL, verbose_name='route setters')),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='climbing_routes', to='climbs.wall', verbose_name='wall')),
            ],
            options={
                'verbose_name': 'climbing route',
                'verbose_name_plural': 'climbing routes',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['is_archived', 'discipline'], name='climbs_clim_is_arch_d5dc96_idx'), models.Index(fields=['wall', 'is_archived'], name='climbs_clim_wall_id_f6f882_idx'), models.Index(fields=['official_grade'], name='climbs_clim_officia_a1a29a_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='climbs_climbingroute_name_ci_uniq'), models.CheckConstraint(condition=models.Q(models.Q(('is_project', True), ('official_grade', '')), models.Q(('is_project', False), models.Q(('official_grade', ''), _negated=True)), _connector='OR'), name='climbs_route_project_grade_consistent')],
            },
        ),
    ]
