# Generated by Django 5.2.17 on 2026-08-27 12:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ascent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='date')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('proposed_grade', models.PositiveSmallIntegerField(help_text='Encoded French grade with a decimal from 0 to 9.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(349)], verbose_name='proposed grade')),
                ('attempt_type', models.CharField(choices=[('onsight', 'Onsight'), ('flash', 'Flash'), ('count', 'Number of attempts'), ('unknown', 'N.D.')], default='unknown', max_length=10, verbose_name='attempt result')),
                ('attempt_count', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='attempt count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('climbing_route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ascents', to='climbs.climbingroute', verbose_name='climbing route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ascents', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'ascent',
                'verbose_name_plural': 'ascents',
                'ordering': ('-date', '-created_at'),
                'indexes': [models.Index(fields=['user', 'date'], name='climbs_asce_user_id_eae188_idx'), models.Index(fields=['climbing_route', 'date'], name='climbs_asce_climbin_e9b503_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'climbing_route'), name='climbs_ascent_user_route_uniq'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='climbs_ascent_rating_range'), models.CheckConstraint(condition=models.Q(('proposed_grade__gte', 0), ('proposed_grade__lte', 349)), name='climbs_ascent_proposed_grade_range'), models.CheckConstraint(condition=models.Q(models.Q(('attempt_count__gte', 1), ('attempt_count__isnull', False), ('attempt_type', 'count')), models.Q(models.Q(('attempt_type', 'count'), _negated=True), ('attempt_count__isnull', True)), _connector='OR'), name='climbs_ascent_attempt_consistent')],
            },
        ),
    ]
