# Generated by Django 5.2.17 on 2026-08-27 12:39

import apps.climbs.annotations
import apps.climbs.images
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0002_ascent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to=apps.climbs.images.route_image_upload_path, validators=[apps.climbs.images.validate_route_image], verbose_name='image')),
                ('annotations', models.JSONField(default=apps.climbs.annotations.empty_route_annotation, validators=[apps.climbs.annotations.validate_route_annotation], verbose_name='annotations')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('climbing_route', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='route_image', to='climbs.climbingroute', verbose_name='climbing route')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_route_images', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'route image',
                'verbose_name_plural': 'route images',
                'ordering': ('climbing_route__name',),
            },
        ),
    ]
