# Generated by Django 5.2.17 on 2026-08-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0003_routeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbingroute',
            name='discipline',
            field=models.CharField(choices=[('route', 'Routes'), ('boulder', 'Boulder')], max_length=10, verbose_name='type'),
        ),
    ]
