# Generated by Django 5.2.17 on 2026-09-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0004_alter_climbingroute_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbingroute',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
    ]
