# Generated by Django 5.2.17 on 2026-09-13 20:19

import apps.accounts.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_email_verified_and_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, upload_to=apps.accounts.images.profile_image_upload_path, validators=[apps.accounts.images.validate_profile_image], verbose_name='profile image'),
        ),
    ]
