# Generated by Django 5.2.17 on 2026-08-27 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('archive', 'Archived'), ('restore', 'Restored'), ('delete', 'Deleted'), ('role_change', 'Role changed'), ('upload', 'Uploaded'), ('replace', 'Replaced'), ('annotate', 'Annotated')], max_length=20, verbose_name='action')),
                ('entity_type', models.CharField(max_length=50, verbose_name='entity type')),
                ('entity_id', models.CharField(max_length=64, verbose_name='entity ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL, verbose_name='actor')),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log entries',
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['created_at'], name='core_auditl_created_711d72_idx'), models.Index(fields=['entity_type', 'entity_id'], name='core_auditl_entity__32d462_idx')],
            },
        ),
    ]
